In [ ]:
import pandas as pd

In [131]:
df = pd.read_csv("https://raw.githubusercontent.com/Idanlau/Cloudera_Hackathon/Word-Encoding/artist_fame.csv")
df

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1       price  \
0             0             0               0  28.500 USD   
1             1             1               1   3.000 USD   
2             2             2               2   5.000 USD   
3             3             3               3   5.000 USD   
4             4             4               4   2.500 USD   
..          ...           ...             ...         ...   
749         749           749             749     680 USD   
750         750           750             750   1.275 USD   
751         751           751             751     680 USD   
752         752           752             752   1.275 USD   
753         753           753             753     680 USD   

                       artist  fame                  title  \
0             Tommaso Ottieri   0.0         Bayreuth Opera   
1           Pavel Tchelitchew   0.0  Drawings of the Opera   
2                   Leo Gabin  98.0        Two on Sidewalk   
3           Matthias Dornfeld  88.0            Blumenszene   
4    Alexis Marguerite Teplin   0.0   Feverish Embarkation   
..                        ...   ...                    ...   
749                 Jane Kent   0.0       Miracle Grow #17   
750                Gary Bower   0.0           Rolph Series   
751                 Jane Kent   0.0               Untitled   
752              T. L. Solien   0.0                Juniper   
753                 John Duff   0.0         Untitled Print   

                 yearCreation  \
0                        2021   
1    First Half 20th Century    
2                        2016   
3                        2010   
4                        2001   
..                        ...   
749                      2012   
750                      1970   
751                      2012   
752                      1986   
753                      1975   

                                                signed  \
0                                      Signed on verso   
1                                    Signed and titled   
2                    Signed, titled and dated on verso   
3    Signed, titled and dated on the reverse with t...   
4                                      Signed on verso   
..                                                 ...   
749                   Signed and dated on lower right.   
750                                              [nan]   
751                                              [nan]   
752                                              [nan]   
753              Signed, dated and numbered in pencil.   

                                             condition        period  \
0                 This work is in excellent condition.  Contemporary   
1    Not examined out of frame.No obvious signs of ...      Post-War   
2                 This work is in excellent condition.  Contemporary   
3    This work is in excellent condition.There is m...  Contemporary   
4                 This work is in excellent condition.  Contemporary   
..                                                 ...           ...   
749  Not examined out of frame.No obvious signs of ...  Contemporary   
750  Not examined out of frame.Significant undulati...  Contemporary   
751  Not examined out of frame.No apparent imperfec...  Contemporary   
752  Not examined outside of frame.Pinholes at edge...  Contemporary   
753  Not examined out of frame.Scattered surface sc...        Modern   

                  movement  
0                  Baroque  
1               Surrealism  
2                 Abstract  
3                 Abstract  
4                 Abstract  
..                     ...  
749               Abstract  
750  Geometric Abstraction  
751  Geometric Abstraction  
752               Abstract  
753  Geometric Abstraction  

[754 rows x 12 columns]

In [132]:
movement_df = pd.get_dummies(df['movement'])
period_df = pd.get_dummies(df['period'])
movement_df.drop(columns='[nan]',inplace=True)
period_df.drop(columns='[nan]',inplace=True)

In [133]:
df.drop(columns='movement',inplace=True)
df.drop(columns='period',inplace=True)

In [134]:
df = df.join(movement_df)

In [135]:
df = df.join(period_df)

In [136]:
df

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1       price  \
0             0             0               0  28.500 USD   
1             1             1               1   3.000 USD   
2             2             2               2   5.000 USD   
3             3             3               3   5.000 USD   
4             4             4               4   2.500 USD   
..          ...           ...             ...         ...   
749         749           749             749     680 USD   
750         750           750             750   1.275 USD   
751         751           751             751     680 USD   
752         752           752             752   1.275 USD   
753         753           753             753     680 USD   

                       artist  fame                  title  \
0             Tommaso Ottieri   0.0         Bayreuth Opera   
1           Pavel Tchelitchew   0.0  Drawings of the Opera   
2                   Leo Gabin  98.0        Two on Sidewalk   
3           Matthias Dornfeld  88.0            Blumenszene   
4    Alexis Marguerite Teplin   0.0   Feverish Embarkation   
..                        ...   ...                    ...   
749                 Jane Kent   0.0       Miracle Grow #17   
750                Gary Bower   0.0           Rolph Series   
751                 Jane Kent   0.0               Untitled   
752              T. L. Solien   0.0                Juniper   
753                 John Duff   0.0         Untitled Print   

                 yearCreation  \
0                        2021   
1    First Half 20th Century    
2                        2016   
3                        2010   
4                        2001   
..                        ...   
749                      2012   
750                      1970   
751                      2012   
752                      1986   
753                      1975   

                                                signed  \
0                                      Signed on verso   
1                                    Signed and titled   
2                    Signed, titled and dated on verso   
3    Signed, titled and dated on the reverse with t...   
4                                      Signed on verso   
..                                                 ...   
749                   Signed and dated on lower right.   
750                                              [nan]   
751                                              [nan]   
752                                              [nan]   
753              Signed, dated and numbered in pencil.   

                                             condition  ...  Realism  \
0                 This work is in excellent condition.  ...        0   
1    Not examined out of frame.No obvious signs of ...  ...        0   
2                 This work is in excellent condition.  ...        0   
3    This work is in excellent condition.There is m...  ...        0   
4                 This work is in excellent condition.  ...        0   
..                                                 ...  ...      ...   
749  Not examined out of frame.No obvious signs of ...  ...        0   
750  Not examined out of frame.Significant undulati...  ...        0   
751  Not examined out of frame.No apparent imperfec...  ...        0   
752  Not examined outside of frame.Pinholes at edge...  ...        0   
753  Not examined out of frame.Scattered surface sc...  ...        0   

     Romanticism  Social Realism  Street Art  Surrealism  Traditional  \
0              0               0           0           0            0   
1              0               0           0           1            0   
2              0               0           0           0            0   
3              0               0           0           0            0   
4              0               0           0           0            0   
..           ...             ...         ...         ...          ...   
749            0               0           0           0 

In [137]:
df['yearCreation'] = pd.to_numeric(df['yearCreation'],errors = "coerce")
nan_count = df['yearCreation'].isna().sum().sum()
#print(nan_count) #104/753 = around 13.8 percent of data missing for years!
df['yearCreation'] = df['yearCreation'].fillna(df['yearCreation'].median()) #Fill it with the median, any better approaches?
df['yearCreation']

0      2021.0
1      1993.0
2      2016.0
3      2010.0
4      2001.0
        ...  
749    2012.0
750    1970.0
751    2012.0
752    1986.0
753    1975.0
Name: yearCreation, Length: 754, dtype: float64

In [138]:
df['price'] = df['price'].str.replace("USD","") #Dropping the USD string so its just numbers
df['price'] = df['price'].str.replace(".","")
df['price'] = pd.to_numeric(df['price'])
df['price']

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  


0      28500
1       3000
2       5000
3       5000
4       2500
       ...  
749      680
750     1275
751      680
752     1275
753      680
Name: price, Length: 754, dtype: int64

In [139]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
condition = vectorizer.fit_transform(df['condition'])
condition

<754x747 sparse matrix of type '<class 'numpy.int64'>'
	with 10768 stored elements in Compressed Sparse Row format>

In [140]:
vectorizer.get_feature_names_out()

array(['005', '10', '1143', '1200', '124', '15', '170', '1940', '200',
       '25619', '27', '307', '40', '44', '4500', '63', '635', '6c13m',
       '89', '900', 'above', 'abraded', 'abrasion', 'abrasions',
       'accretion', 'accretions', 'across', 'additional', 'address',
       'adhered', 'adherence', 'adhesions', 'adhesive', 'affixed',
       'aforementioned', 'age', 'agfa', 'alexander', 'all', 'along',
       'although', 'an', 'and', 'annotated', 'another', 'anything', 'aoz',
       'apart', 'apparent', 'appear', 'appearance', 'appears',
       'application', 'appropriately', 'approximately', 'are', 'area',
       'areas', 'arm', 'around', 'art', 'artist', 'artminor', 'artwork',
       'as', 'aside', 'associated', 'at', 'attached', 'attributable',
       'away', 'b625', 'back', 'background', 'backing', 'bar', 'barbara',
       'be', 'been', 'bend', 'bernhard', 'between', 'black', 'blemish',
       'blind', 'blue', 'board', 'bois', 'book', 'both', 'bottom', 'bow',
       'bowed', 

In [141]:
print(condition.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [142]:
condition_labels = pd.DataFrame(condition.toarray(),columns=vectorizer.get_feature_names())
condition_labels

/home/cdsw/.local/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


005  10  1143  1200  124  15  170  1940  200  25619  ...  work  working  \
0      0   0     0     0    0   0    0     0    0      0  ...     1        0   
1      0   0     0     0    0   0    0     0    0      0  ...     0        0   
2      0   0     0     0    0   0    0     0    0      0  ...     1        0   
3      0   0     0     0    0   0    0     0    0      0  ...     2        0   
4      0   0     0     0    0   0    0     0    0      0  ...     1        0   
..   ...  ..   ...   ...  ...  ..  ...   ...  ...    ...  ...   ...      ...   
749    0   0     0     0    0   0    0     0    0      0  ...     0        0   
750    0   0     0     0    0   0    0     0    0      0  ...     0        0   
751    0   0     0     0    0   0    0     0    0      0  ...     0        0   
752    0   0     0     0    0   0    0     0    0      0  ...     0        0   
753    0   0     0     0    0   0    0     0    0      0  ...     0        0   

     works  worn  wrapped  wrinkles  written  yellowed  yellowing  york  
0        0     0        0         0        0         0          0     0  
1        1     0        0         0        0         0          0     0  
2        0     0        0         0        0         0          0     0  
3        0     0        0         0        0         0          0     0  
4        0     0        0         0        0         0          0     0  
..     ...   ...      ...       ...      ...       ...        ...   ...  
749      0     0        0         0        0         0          0     0  
750      0     0        0         0        0         0          0     0  
751      0     0        0         0        0         0          0     0  
752      0     0        0         0        0         0          0     0  
753      0     0        0         0        0         0          0     0  

[754 rows x 747 columns]

In [143]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer2 = CountVectorizer()
signed = vectorizer2.fit_transform(df['signed'])
signed

<754x501 sparse matrix of type '<class 'numpy.int64'>'
	with 4175 stored elements in Compressed Sparse Row format>

In [144]:
vectorizer2.get_feature_names_out()

array(['00', '02', '05', '08', '10', '100', '105', '11', '12', '129',
       '14', '15', '16', '17', '18', '1892', '1911', '1921', '1946',
       '1959', '1962', '1964', '1965', '1971', '1975', '1976', '1979',
       '1980', '1981', '1985', '1986', '1987', '1988', '1989', '1990',
       '1991', '1993', '1998', '20', '2000', '2001', '2002', '2003',
       '2005', '2010', '2011', '2012', '2016', '21', '22', '25', '26',
       '27', '29', '2982', '30', '301', '31', '33', '33600j', '35', '367',
       '37', '471', '50', '50th', '60', '71', '74', '75', '76', '77',
       '78', '79', '80', '81together', '85', '86', '87', '89', '90',
       '94115', '97', '98', '99', 'accompanied', 'acrylic', 'ad',
       'affixed', 'afternoon', 'again', 'alaskan', 'albert', 'alex',
       'ali', 'all', 'along', 'also', 'amadee', 'amedeo', 'and',
       'annotated', 'annotation', 'ap', 'apel', 'archive', 'art',
       'artist', 'ashforth', 'ashworth', 'at', 'attached', 'aug',
       'authenticity', 'ax', 'bac

In [145]:
signed_labels = pd.DataFrame(signed.toarray(),columns=vectorizer2.get_feature_names())
signed_labels

/home/cdsw/.local/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


00  02  05  08  10  100  105  11  12  129  ...  whiteford  widow  \
0     0   0   0   0   0    0    0   0   0    0  ...          0      0   
1     0   0   0   0   0    0    0   0   0    0  ...          0      0   
2     0   0   0   0   0    0    0   0   0    0  ...          0      0   
3     0   0   0   0   0    0    0   0   0    0  ...          0      0   
4     0   0   0   0   0    0    0   0   0    0  ...          0      0   
..   ..  ..  ..  ..  ..  ...  ...  ..  ..  ...  ...        ...    ...   
749   0   0   0   0   0    0    0   0   0    0  ...          0      0   
750   0   0   0   0   0    0    0   0   0    0  ...          0      0   
751   0   0   0   0   0    0    0   0   0    0  ...          0      0   
752   0   0   0   0   0    0    0   0   0    0  ...          0      0   
753   0   0   0   0   0    0    0   0   0    0  ...          0      0   

     wildlife  william  with  wm  work  working  written  york  
0           0        0     0   0     0        0        0     0  
1           0        0     0   0     0        0        0     0  
2           0        0     0   0     0        0        0     0  
3           0        0     1   0     0        0        0     0  
4           0        0     0   0     0        0        0     0  
..        ...      ...   ...  ..   ...      ...      ...   ...  
749         0        0     0   0     0        0        0     0  
750         0        0     0   0     0        0        0     0  
751         0        0     0   0     0        0        0     0  
752         0        0     0   0     0        0        0     0  
753         0        0     0   0     0        0        0     0  

[754 rows x 501 columns]

In [146]:
df.drop(columns='signed',inplace=True)
df.drop(columns='condition',inplace=True)
df.drop(columns='artist',inplace=True)

In [147]:
signed_labels = signed_labels.astype(int)
condition_labels = condition_labels.astype(int)

In [148]:
df = df.join(condition_labels)

In [149]:
df

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  price  fame  \
0             0             0               0  28500   0.0   
1             1             1               1   3000   0.0   
2             2             2               2   5000  98.0   
3             3             3               3   5000  88.0   
4             4             4               4   2500   0.0   
..          ...           ...             ...    ...   ...   
749         749           749             749    680   0.0   
750         750           750             750   1275   0.0   
751         751           751             751    680   0.0   
752         752           752             752   1275   0.0   
753         753           753             753    680   0.0   

                     title  yearCreation  Abstract  Abstract Expressionism  \
0           Bayreuth Opera        2021.0         0                       0   
1    Drawings of the Opera        1993.0         0                       0   
2          Two on Sidewalk        2016.0         1                       0   
3              Blumenszene        2010.0         1                       0   
4     Feverish Embarkation        2001.0         1                       0   
..                     ...           ...       ...                     ...   
749       Miracle Grow #17        2012.0         1                       0   
750           Rolph Series        1970.0         0                       0   
751               Untitled        2012.0         0                       0   
752                Juniper        1986.0         1                       0   
753         Untitled Print        1975.0         0                       0   

     Art Brut  ...  work  working  works  worn  wrapped  wrinkles  written  \
0           0  ...     1        0      0     0        0         0        0   
1           0  ...     0        0      1     0        0         0        0   
2           0  ...     1        0      0     0        0         0        0   
3           0  ...     2        0      0     0        0         0        0   
4           0  ...     1        0      0     0        0         0        0   
..        ...  ...   ...      ...    ...   ...      ...       ...      ...   
749         0  ...     0        0      0     0        0         0        0   
750         0  ...     0        0      0     0        0         0        0   
751         0  ...     0        0      0     0        0         0        0   
752         0  ...     0        0      0     0        0         0        0   
753         0  ...     0        0      0     0        0         0        0   

     yellowed  yellowing  york  
0           0          0     0  
1           0          0     0  
2           0          0     0  
3           0          0     0  
4           0          0     0  
..        ...        ...   ...  
749         0          0     0  
750         0          0     0  
751         0          0     0  
752         0          0     0  
753         0          0     0  

[754 rows x 791 columns]

In [150]:
df = df.join(signed_labels,lsuffix="_left", rsuffix="_right", how='right')

In [151]:
df = df.drop(df.columns[[0, 1, 2,5]],axis = 1)

In [152]:
df

price  fame  yearCreation  Abstract  Abstract Expressionism  Art Brut  \
0    28500   0.0        2021.0         0                       0         0   
1     3000   0.0        1993.0         0                       0         0   
2     5000  98.0        2016.0         1                       0         0   
3     5000  88.0        2010.0         1                       0         0   
4     2500   0.0        2001.0         1                       0         0   
..     ...   ...           ...       ...                     ...       ...   
749    680   0.0        2012.0         1                       0         0   
750   1275   0.0        1970.0         0                       0         0   
751    680   0.0        2012.0         0                       0         0   
752   1275   0.0        1986.0         1                       0         0   
753    680   0.0        1975.0         0                       0         0   

     Art Deco  Art Nouveau  Baroque  Conceptual   ...  whiteford  widow  \
0           0            0        1            0  ...          0      0   
1           0            0        0            0  ...          0      0   
2           0            0        0            0  ...          0      0   
3           0            0        0            0  ...          0      0   
4           0            0        0            0  ...          0      0   
..        ...          ...      ...          ...  ...        ...    ...   
749         0            0        0            0  ...          0      0   
750         0            0        0            0  ...          0      0   
751         0            0        0            0  ...          0      0   
752         0            0        0            0  ...          0      0   
753         0            0        0            0  ...          0      0   

     wildlife  william  with_right  wm  work_right  working_right  \
0           0        0           0   0           0              0   
1           0        0           0   0           0              0   
2           0        0           0   0           0              0   
3           0        0           1   0           0              0   
4           0        0           0   0           0              0   
..        ...      ...         ...  ..         ...            ...   
749         0        0           0   0           0              0   
750         0        0           0   0           0              0   
751         0        0           0   0           0              0   
752         0        0           0   0           0              0   
753         0        0           0   0           0              0   

     written_right  york_right  
0                0           0  
1                0           0  
2                0           0  
3                0           0  
4                0           0  
..             ...         ...  
749              0           0  
750              0           0  
751              0           0  
752              0           0  
753              0           0  

[754 rows x 1288 columns]

In [161]:
from sklearn.model_selection import train_test_split
X = df.loc[:, ~df.columns.isin(['artist', 'title', 'signed','condition','title_left','price'])]
Y = df["price"]
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [162]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
regr = RandomForestRegressor(max_depth=20, random_state=0)
regr.fit(X_train,y_train)
print("Training Score: ",regr.score(X_train,y_train))
print("Testing Score: ",regr.score(X_test,y_test))
print("Testing Mean Absolute Error: ", mean_absolute_error(y_test,regr.predict(X_test)))

Training Score:  0.8927311949833197
Testing Score:  0.2566512358100401
Testing Mean Absolute Error:  3071.878462468827


In [163]:
import numpy as np
importances = regr.feature_importances_
sorted_indices = np.argsort(importances)[::-1]
 
feat_labels = df.columns[1:]
 
for f in range(40):
    print("%2d) %-*s %f" % (f + 1, 10,
                            feat_labels[sorted_indices[f]],
                            importances[sorted_indices[f]]),"index: ",df.columns.get_loc(str(feat_labels[sorted_indices[f]])))

 1) fame       0.124871 index:  1
 2) occasional 0.107238 index:  478
 3) Photorealism 0.070055 index:  24
 4) yearCreation 0.065128 index:  2
 5) red        0.059889 index:  1197
 6) Pop Art    0.058866 index:  25
 7) norman     0.055948 index:  1151
 8) vath       0.017984 index:  1265
 9) that       0.017840 index:  698
10) impressions 0.017696 index:  361
11) richard    0.015565 index:  1201
12) thin       0.013791 index:  704
13) oil_left   0.013485 index:  482
14) thanks     0.013385 index:  1250
15) mixed      0.013216 index:  446
16) Abstract Expressionism 0.012340 index:  4
17) examples   0.012272 index:  265
18) provided   0.012168 index:  553
19) amedeo     0.010974 index:  886
20) foxing     0.010721 index:  297
21) dinged     0.010675 index:  224
22) bonakdar   0.009255 index:  925
23) lee        0.008886 index:  1099
24) working_left 0.008052 index:  778
25) fresh      0.007810 index:  303
26) dyf        0.007809 index:  980
27) date       0.007790 index:  963
28) Contemp

In [164]:
from sklearn.linear_model import LinearRegression
import numpy as np
regr = LinearRegression()
regr.fit(X_train,y_train)
print("Training Score: ",regr.score(X_train,y_train))
print("Testing Score: ",regr.score(X_test,y_test))
print("Testing Mean Absolute Error: ", mean_absolute_error(y_test,regr.predict(X_test)))

Training Score:  0.5541669884777928
Testing Score:  -6.710022526523216
Testing Mean Absolute Error:  14553.908692708004


In [165]:
from sklearn.neighbors import KNeighborsRegressor
regr = KNeighborsRegressor()
regr.fit(X_train,y_train)
print("Training Score: ",regr.score(X_train,y_train))
print("Testing Score: ",regr.score(X_test,y_test))
print("Testing Mean Absolute Error: ", mean_absolute_error(y_test,regr.predict(X_test)))

Training Score:  0.3637762167948779
Testing Score:  -0.013745124106342654
Testing Mean Absolute Error:  4797.854304635762


In [166]:
# import libraries
from sklearn.feature_selection import RFE

# define RFE
rfe = RFE(estimator=RandomForestRegressor(max_depth=20, random_state=0),n_features_to_select=15)
# fit RFE
rfe.fit(X, Y)


RFE(estimator=RandomForestRegressor(max_depth=20, random_state=0),
    n_features_to_select=15)

In [167]:
forest = RandomForestRegressor(max_depth=20, random_state=0)
_ = forest.fit(rfe.transform(X_train), y_train)
print("Training Score: ",forest.score(rfe.transform(X_train),y_train))
print("Testing Score: ",forest.score(rfe.transform(X_test),y_test))
print("Testing Mean Absolute Error: ", mean_absolute_error(y_test,forest.predict(rfe.transform(X_test))))

Training Score:  0.8848602594339088
Testing Score:  0.17578211610545946
Testing Mean Absolute Error:  3307.5716269283275


In [168]:
import numpy as np
importances = forest.feature_importances_
sorted_indices = np.argsort(importances)[::-1]
 
feat_labels = df.columns[1:]
 
for f in range(15):
    print("%2d) %-*s %f" % (f + 1, 10,
                            feat_labels[sorted_indices[f]],
                            importances[sorted_indices[f]]),"index: ",df.columns.get_loc(str(feat_labels[sorted_indices[f]])))

 1) fame       0.184862 index:  1
 2) yearCreation 0.145194 index:  2
 3) Art Nouveau 0.133943 index:  7
 4) Abstract Expressionism 0.078284 index:  4
 5) Expressionism 0.074199 index:  12
 6) Feminist Art  0.071030 index:  13
 7) Abstract   0.070493 index:  3
 8) Conceptual  0.042495 index:  9
 9) Impressionism 0.042036 index:  15
10) Baroque    0.040333 index:  8
11) Geometric Abstraction 0.033721 index:  14
12) Cubism     0.023724 index:  10
13) Art Brut   0.021485 index:  5
14) Environmental Art 0.020248 index:  11
15) Art Deco   0.017954 index:  6


In [169]:
print(X.shape[1])

1286


In [170]:
from joblib import dump, load
dump(forest, 'ArtNum.joblib') 

['ArtNum.joblib']

In [1]:
print("The model complexity has been greatly reduced using recursive feature elimination from 1286 features down to 15 features. However the simplified model estimation is around 300 dollars worse which is about 10 percent worse.")

The model complexity has been greatly reduced using recursive feature elimination from 1286 features down to 15 features. However the simplified model estimation is around 300 dollars worse which is about 10 percent worse.
